# Generated by Django 4.2.7 on 2026-02-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_intro_url',
            field=models.URLField(blank=True, help_text='YouTube URL for intro preview e.g. https://www.youtube.com/watch?v=xxxxx', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL e.g. https://www.youtube.com/watch?v=xxxxx', max_length=500, null=True),
        ),
    ]
